apiVersion: v1
kind: Service
metadata:
  name: kubernetes-assignment-service
spec:
  selector:
    app: kubernetes-assignment
  ports:
  - protocol: TCP
    port: 80          # External port
    targetPort: 8080  # Port your container is listening on
    nodePort: 30000   # NodePort (range: 30000-32767)
  type: NodePort      # Exposes the service on a static port on each node
